name: "Build and test"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0

      - name: Install nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = ${{ matrix.system }}

      - name: Configure cachix
        uses: cachix/cachix-action@v14
        with:
          name: kdevlab-nix-portable
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt@sha256:8de6f2decb92e9001d094534bf8a92880c175bd5dfb4a9d8579f26f09821cfa2
          platforms: all

      - name: Install binfmt support
        run: sudo apt-get install -y

      - name: Build
        run: nix build -L .#defaultPackage.${{ matrix.system }}

      - name: Archive result
        uses: actions/upload-artifact@v4
        with:
          name: nix-portable-${{ matrix.system }}
          path: result/bin/nix-portable

  test_github:
    name: Test inside github action
    needs: build
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0

      - name: Install nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Test
        run: nix run -L .#job-local

  pre-release:
    name: Pre-release
    needs: test_github
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0

      - name: Install nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = aarch64-linux

      - name: Configure cachix
        uses: cachix/cachix-action@v14
        with:
          skipPush: true
          name: kdevlab-nix-portable
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install binfmt support
        run: sudo apt-get install -y

      - name: Generate pre-release
        run: nix build -L .#release

      - name: Publish pre-release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          prerelease: true
          name: "Development Build"
          append_body: true
          files: |
            result/nix-portable-*
