name: Update dependencies
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup shit
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: rampage
          witness-carnage: true
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update
        run: |
          nix flake update
          ./update.py
