name: Update dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true
      - name: Install nix
        uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update
        run: |
          ./update.py
          nix flake update
      - name: Push changes
        run: |
          set -x

          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          STATUS=$(git status -s)
          if [ -n "$STATUS" ]; then
              git add .
              git commit -m "[automatic] $(date) update dependencies"
              git push
          fi
